exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

title: Brennan Moore
description: Building build web applications to help people go about their day in a more awesome way.
url: https://zamiang.com
author:
  name: Brennan Moore
  email: brennanmoore@gmail.com
  github: zamiang
  twitter: zamiang
  gplus: 'https://plus.google.com/u/1/100884430802346698066/posts'
permalink: /:categories/:year/:month/:day/:title
production_url: http://www.zamiang.com

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "smart"]
